common:
    acceptors: 4
    workers: 100

metrics:
    jvm:
        memory: true
        gc: true
        threadState: true
        threadDump: true
        threadDeadlock: true
        fileDescriptors: true

servers:
    ads:
        port: 9090
        enable: true
        ssl: false
        metrics: true
    origin:
        port: 9091
        enable: true
        ssl: false
        responseFile: conf/playlist.m3u8
        metrics: true
    cacheMiss-callback:
        port: 9092
        enable: true
        ssl: false
        metrics: true
    director:
        port: 9093
        enable: true
        ssl: false
        metrics: true
    web-socket:
        port: 9094
        enable: true
        ssl: false
        metrics: true
    content-router:
        port: 9095
        enable: true
        ssl: false
        useLocation: true
        metrics: true
        edgeCaches:
          - namePrefix: ec1
            rangeFrom: 0
            rangeTo: 10
          - namePrefix: ec2
            rangeFrom: 0
            rangeTo: 10